<?php

$define = [
    'TEXT_LABEL_FOCUS_KEYWORD' => 'Focus Keyword',
    'TEXT_LABEL_FOCUS_KEYWORD_PLACEHOLDER' => 'Enter keyword to analyze...',
    'TEXT_GOOGLE_SNIPPET_PREVIEW' => 'Google Snippet Preview',
    'TEXT_GOOGLE_SNIPPET_PREVIEW_TITLE' => 'Product Title',
    'TEXT_GOOGLE_SNIPPET_PREVIEW_DESCRIPTION' => 'Please provide a meta description for this product to ensure search engines display the correct summary.',
    'TEXT_BASIC_SEO' => 'Basic SEO',
    'TEXT_TITLE_META' => 'Title & Meta',
    'TEXT_READABILITY' => 'Readability',

    'JAVASCRIPT_SNIPPET_TITLE_DEFAULT' => 'Product Title',
    'JAVASCRIPT_SNIPPET_DESC_DEFAULT' => 'Meta Description will be automatically generated by Zen Cart. Please provide a meta description for this product to ensure search engines display the correct summary.',

    'JAVASCRIPT_CONTENT_LENGTH_GOOD' => '<strong>Content Length:</strong> The content is %s words long. Good job.',
    'JAVASCRIPT_CONTENT_LENGTH_BAD' => '<strong>Content Length:</strong> The content is %s words long. Consider expanding to at least 300 words.',

    'JAVASCRIPT_INTERNAL_LINKS_GOOD' => '<strong>Internal Links:</strong> You have %s internal links.',
    'JAVASCRIPT_INTERNAL_LINKS_BAD' => '<strong>Internal Links:</strong> No internal links found. Add links to other products or categories.',

    'JAVASCRIPT_EXTERNAL_LINKS_GOOD' => '<strong>External Links:</strong> You have %s outbound links.',
    'JAVASCRIPT_EXTERNAL_LINKS_BAD' => '<strong>External Links:</strong> No outbound links found. Consider linking to a manufacturer or sizing guide.',

    'JAVASCRIPT_KEYWORD_DENSITY_GOOD' => '<strong>Keyword Density:</strong> The focus keyword was found %s times.',
    'JAVASCRIPT_KEYWORD_DENSITY_BAD' => '<strong>Keyword Density:</strong> The focus keyword does not appear in the content.',
    'JAVASCRIPT_KEYWORD_DENSITY_INFO' => '<strong>Keyword Density:</strong> Set a focus keyword to evaluate density.',

    'JAVASCRIPT_TITLE_LENGTH_GOOD' => '<strong>Title Length:</strong> %s chars. Optimal length.',
    'JAVASCRIPT_TITLE_LENGTH_BAD' => '<strong>Title Length:</strong> %s chars. Keep between 40 and 60 characters.',

    'JAVASCRIPT_DESC_LENGTH_GOOD' => '<strong>Description Length:</strong> %s chars. Optimal length.',
    'JAVASCRIPT_DESC_LENGTH_BAD' => '<strong>Description Length:</strong> %s chars. Keep between 120 and 160 characters.',

    'JAVASCRIPT_TITLE_KEYWORD_GOOD' => '<strong>Keyword in Title:</strong> Focus keyword found in meta title.',
    'JAVASCRIPT_TITLE_KEYWORD_BAD' => '<strong>Keyword in Title:</strong> Focus keyword missing from meta title.',

    'JAVASCRIPT_SENTENCE_LENGTH_BASE' => '<strong>Sentence Length:</strong> %s% of sentences contain more than 20 words. ',
    'JAVASCRIPT_SENTENCE_LENGTH_BAD' => 'Try to shorten them.',
    'JAVASCRIPT_SENTENCE_LENGTH_GOOD' => 'Good job.',

    'JAVASCRIPT_READABILITY_BAD' => '<strong>Readability:</strong> Not enough content to provide a reliable readability score.',
];

return $define;
