<?php
/**
 * standalone class to generate llms.txt content
 * @package zx-llms-txt-manager
 * @copyright ZenExpert 2026
 * @version $Id: LlmsTxtGenerator.php 2026 Jan 09 ZenExpert $
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 */
class LlmsTxtGenerator {
    private $title;
    private $summary;
    private $guidance = [];
    private $sections = [];

    public function __construct($title, $summary = '') {
        $this->title = $this->sanitizeMarkdown($title);
        $this->summary = $this->sanitizeMarkdown($summary);
    }

    public function addGuidance($text) {
        if (!empty($text)) {
            // Guidance is usually raw text instructions, but sanitize to be safe
            $this->guidance[] = $this->sanitizeMarkdown($text);
        }
    }

    /**
     * Add a section of Links
     * helper: Clean URLs and Sanitize Text
     */
    public function addLinkSection($heading, $links_array) {
        if (!empty($links_array)) {
            $clean_links = [];
            foreach ($links_array as $link) {
                $clean_links[] = [
                    // URL: Decode &amp; back to &, but do NOT escape markdown chars
                    'url' => htmlspecialchars_decode($link['url']),
                    // Text: Escape special markdown characters
                    'title' => $this->sanitizeMarkdown($link['title']),
                    'desc' => isset($link['desc']) ? $this->sanitizeMarkdown($link['desc']) : ''
                ];
            }

            $this->sections[] = [
                'type' => 'links',
                'heading' => $this->sanitizeMarkdown($heading),
                'content' => $clean_links
            ];
        }
    }

    public function addListSection($heading, $items_array) {
        if (!empty($items_array)) {
            $clean_items = [];
            foreach ($items_array as $item) {
                $clean_items[] = $this->sanitizeMarkdown($item);
            }

            $this->sections[] = [
                'type' => 'list',
                'heading' => $this->sanitizeMarkdown($heading),
                'content' => $clean_items
            ];
        }
    }

    public function generate() {

        $date_string = date("F j, Y, g:i a");
        $output = "Generated by ZenExpert LLMs.txt Generator Plugin, " . $date_string . ", this is an llms.txt file, meant for consumption by LLMs.\n\n";

        $output .= "# " . $this->title . "\n\n";

        if (!empty($this->summary)) {
            $output .= "> " . $this->summary . "\n\n";
        }

        if (!empty($this->guidance)) {
            $output .= "## Guidance\n\n";
            foreach ($this->guidance as $g) {
                $output .= "- " . $g . "\n";
            }
            $output .= "\n";
        }

        foreach ($this->sections as $section) {
            $output .= "## " . $section['heading'] . "\n\n";

            if ($section['type'] == 'links') {
                foreach ($section['content'] as $link) {
                    $output .= "- [" . $link['title'] . "](" . $link['url'] . ")";
                    if (!empty($link['desc'])) {
                        $output .= ": " . $link['desc'];
                    }
                    $output .= "\n";
                }
            } elseif ($section['type'] == 'list') {
                foreach ($section['content'] as $item) {
                    $output .= "- " . $item . "\n";
                }
            }
            $output .= "\n";
        }

        return $output;
    }

    /**
     * Escapes Markdown special characters to prevent formatting errors.
     * Based on Yoast/CommonMark specs.
     * Currently not used, but kept for reference.
     */
    private function sanitizeMarkdownStrict($text) {
        if (empty($text)) return '';

        // Characters to escape: \ ` * _ { } [ ] ( ) # + - . ! |
        $special_chars = [
            '\\', '`', '*', '_', '{', '}', '[', ']', '(', ')', '#', '+', '-', '.', '!', '|', '<', '>'
        ];

        $escaped_chars = [];
        foreach ($special_chars as $char) {
            $escaped_chars[] = '\\' . $char;
        }

        return str_replace($special_chars, $escaped_chars, $text);
    }

    /**
     * Escapes ONLY critical Markdown characters.
     * Relaxed version: Leaves . ! - alone unless dangerous.
     */
    private function sanitizeMarkdown($text) {
        if (empty($text)) return '';

        // 1. Backslash itself must be escaped first
        $text = str_replace('\\', '\\\\', $text);

        // 2. Critical characters that break structure (Links, Images, Code, Emphasis)
        // escape: [ ] ` * _ < >
        $critical_chars = ['[', ']', '`', '*', '_', '<', '>', '#', '|'];

        foreach ($critical_chars as $char) {
            $text = str_replace($char, '\\' . $char, $text);
        }

        return $text;
    }
}
